db:
  username: ${username.value:postgres}
  password: ans851
  driver: PostgresDriver
  url: postgres5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 456
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: INFO
    com.androsor.spring.database.pool.ConnectionPool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: androsor.log
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_trainer
    username: postgres
    password: ans851
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 930487524389-tk665jn5ibe9lkro4et1bf8jh823i9l2.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile
springdoc:
  swagger-ui:
    oauth:
      client-id: 930487524389-tk665jn5ibe9lkro4et1bf8jh823i9l2.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth-redirect.html